version: '3.4'
services:
#  agricolab-project:
#    image: agricolabproject/agricolab-project
#    restart: always
#    build: ./agricolab
#    working_dir: /agricolab
#    environment:
#      TZ: America/Sao_Paulo
#      SPRING_BOOT_ENVIRONMENT: Production
#    ports:
#      - "8080:8080"
#    command: mvn spring-boot:run
#    networks:
#      - agricolab-network
  agricolab-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=grupo18agricolab
      - MYSQL_USER=agricolab
      - MYSQL_DATABASE=dbagricolab
    ports:
      - "3308:3308"
networks:
    agricolab-network:
        driver: bridge